from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from sourcebound.errors import ConfigurationError
from sourcebound.accessibility import check_accessibility
from sourcebound.manifest import load_manifest
from sourcebound.mdx import parse_mdx
from sourcebound.projections import render_projections, write_projections
from sourcebound.standard import load_default_pack
from sourcebound.visuals import load_visual_record


MANIFEST = """\
version: 1
bindings:
  - id: overview
    type: region
    doc: README.md
    region: overview
    extractor: file
    source: {path: source.txt}
    renderer: scalar
projections:
  visuals:
    - id: queue-flow
      source: docs/visuals/queue-flow.yml
      human_output: docs/generated/queue-flow.mdx
      agent_output: .sourcebound/visuals/queue-flow.md
"""

RECORD = """\
schema: sourcebound.visual.v1
id: queue-flow
kind: screenshot
src: docs/assets/queue-light.png
src_dark: docs/assets/queue-dark.png
width: 1200
height: 800
alt: Queue dashboard with the worker status panel open
caption: The worker panel shows which queue owns the stalled job.
description: |
  The dashboard lists three queues. The selected queue opens a worker panel
  whose status and retry action apply only to that queue.
annotations:
  - id: queue-selector
    x: 18.5
    y: 22
    title: Queue selector
    description: Selects the queue whose workers and jobs appear.
  - id: retry-action
    x: 81
    y: 74.25
    title: Retry action
    description: Retries the selected failed job after confirmation.
"""


def _repo(tmp_path: Path) -> Path:
    root = tmp_path / "repo"
    (root / "docs/visuals").mkdir(parents=True)
    (root / "docs/assets").mkdir(parents=True)
    (root / "source.txt").write_text("Bound overview\n")
    (root / "README.md").write_text(
        "# Fixture\n\n"
        "<!-- sourcebound:begin overview -->\n"
        "Bound overview\n"
        "<!-- sourcebound:end overview -->\n"
    )
    (root / ".sourcebound.yml").write_text(MANIFEST)
    (root / "docs/visuals/queue-flow.yml").write_text(RECORD)
    (root / "docs/assets/queue-light.png").write_bytes(b"\x89PNG\r\n\x1a\nlight")
    (root / "docs/assets/queue-dark.png").write_bytes(b"\x89PNG\r\n\x1a\ndark")
    subprocess.run(["git", "init", "-q", str(root)], check=True)
    subprocess.run(["git", "-C", str(root), "add", "."], check=True)
    return root


def test_visual_record_projects_human_and_agent_surfaces(tmp_path: Path) -> None:
    root = _repo(tmp_path)
    manifest = load_manifest(root / ".sourcebound.yml")

    projection_set = render_projections(root, manifest)

    human = projection_set.files[Path("docs/generated/queue-flow.mdx")]
    agent = projection_set.files[Path(".sourcebound/visuals/queue-flow.md")]
    assert 'data-sourcebound-visual="sourcebound.visual.v1"' in human
    assert "{/* sourcebound:role reference */}" in human
    assert 'aria-label="1: Queue selector"' in human
    assert "left: '18.5%'" in human
    assert any(node.name == "figure" for node in parse_mdx(human).nodes)
    assert "../../docs/assets/queue-light.png" in agent
    assert "## Complete text equivalent" in agent
    assert "The dashboard lists three queues." in agent
    assert "1. **Queue selector** (`x=18.5%`, `y=22%`)" in agent
    assert projection_set.digests[Path("docs/generated/queue-flow.mdx")] == (
        projection_set.digests[Path(".sourcebound/visuals/queue-flow.md")]
    )


def test_write_visual_projections_creates_both_outputs(tmp_path: Path) -> None:
    root = _repo(tmp_path)
    manifest = load_manifest(root / ".sourcebound.yml")

    written = write_projections(root, manifest)

    assert written == (
        Path(".sourcebound/visuals/queue-flow.md"),
        Path("docs/generated/queue-flow.mdx"),
    )
    assert all((root / path).is_file() for path in written)


def test_markdown_human_projection_uses_native_html_semantics(tmp_path: Path) -> None:
    root = _repo(tmp_path)
    manifest_path = root / ".sourcebound.yml"
    manifest_path.write_text(
        manifest_path.read_text().replace(
            "human_output: docs/generated/queue-flow.mdx",
            "human_output: docs/generated/queue-flow.md",
        )
    )

    human = render_projections(
        root, load_manifest(manifest_path)
    ).files[Path("docs/generated/queue-flow.md")]

    assert human.startswith("<!-- generated by Sourcebound")
    assert "<!-- sourcebound:role reference -->" in human
    assert 'style="position: relative;' in human
    assert 'srcset="../assets/queue-dark.png"' in human
    assert check_accessibility(
        "docs/generated/queue-flow.md", human, load_default_pack()
    ) == []


@pytest.mark.parametrize(
    ("replacement", "message"),
    [
        ("schema: sourcebound.visual.v2", "must use schema"),
        ("id: other-flow", "does not match record id"),
        ("x: 18.5", "duplicate visual annotation id"),
        ("x: 118.5", "number from 0 through 100"),
        ("src: ../outside.png", "HTTPS or repository-relative"),
        ("src: docs/assets/queue light.png", "Markdown link delimiters"),
    ],
)
def test_visual_record_rejects_ambiguous_or_unsafe_data(
    tmp_path: Path,
    replacement: str,
    message: str,
) -> None:
    root = _repo(tmp_path)
    record_path = root / "docs/visuals/queue-flow.yml"
    text = record_path.read_text()
    if replacement == "x: 18.5":
        text = text.replace("id: retry-action", "id: queue-selector")
    elif replacement.startswith("schema:"):
        text = text.replace("schema: sourcebound.visual.v1", replacement)
    elif replacement.startswith("id:"):
        text = text.replace("id: queue-flow", replacement, 1)
    elif replacement.startswith("src:"):
        text = text.replace("src: docs/assets/queue-light.png", replacement)
    else:
        text = text.replace("x: 18.5", replacement)
    record_path.write_text(text)

    with pytest.raises(ConfigurationError, match=message):
        load_visual_record(record_path, "queue-flow")


def test_visual_projection_requires_existing_assets(tmp_path: Path) -> None:
    root = _repo(tmp_path)
    (root / "docs/assets/queue-dark.png").unlink()

    with pytest.raises(ConfigurationError, match="visual asset does not exist"):
        render_projections(root, load_manifest(root / ".sourcebound.yml"))


def test_visual_projection_rejects_an_asset_symlink_that_escapes(
    tmp_path: Path,
) -> None:
    root = _repo(tmp_path)
    outside = tmp_path / "outside.png"
    outside.write_bytes(b"\x89PNG\r\n\x1a\n")
    asset = root / "docs/assets/queue-light.png"
    asset.unlink()
    asset.symlink_to(outside)

    with pytest.raises(ConfigurationError, match="visual asset escapes"):
        render_projections(root, load_manifest(root / ".sourcebound.yml"))
